---
- name: restart_node_exporter_service
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes

- name: restart_apcupsd_exporter
  systemd:
    name: apcupsd_exporter
    state: restarted
    daemon_reload: yes
