---
- name: reload_systemd
  systemd:
    daemon_reload: yes

- name: reboot_host
  reboot:
    msg: "Rebooting to apply power optimization kernel parameters"
    pre_reboot_delay: 5

- name: restart_apcupsd
  systemd:
    name: apcupsd
    state: restarted
